spring:
  profiles:
    include: janus, oauth2, jwt, mail, mysql
server:
  port: 8080 # 서버 주소
springdoc:
  swagger-ui:
    path: /api-docs # swagger-ui 접근 경로에 대한 별칭
  paths-to-match:
    - /api/** # swagger-ui에 표시할 api의 엔드포인트 패턴
  show-login-endpoint: true
default:
  image:
#   서버 경로 프로젝트 위치로 지정
    upload-address: "C:/GitWorkspace/organization/ConferenceProject/BackEnd/broadcast"
    address: "/images/profile/anonymous.png"
client:
  success-url: "http://127.0.0.1:3030"
  fail-url: "http://127.0.0.1:3030/signin"
