spring:
  profiles:
    include: janus, oauth2, jwt
    group:
      db: mysql, mongo
    active: db
  config:
    import:
      - classpath:/db/application-mysql.yml
      - classpath:/db/application-mongo.yml
server:
  port: 8080 # 서버 주소
  tomcat:
    threads:
      max: 200 # 생성할 수 있는 thread의 총 개수
      min-spare: 10 # 항상 활성화 되어있는(idle) thread의 개수
    accept-count: 100
    connection-timeout: 10000

